### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Jmgr** [DavidXanatos/NeoScriptTools#1]
Hi, I'm trying to compile this project to see if I could integrate it (amazing work by the way, not having a visual debugger has been a blocker for me to migrate to Qt6!), but it seems that some files are missing, for instance `qv4engine_p.h`.

**Comment by DavidXanatos** [comment]
qv4engine_p.h is a private qt include you need to add module qml-private to get those files into your include paths

**Comment by Jmgr** [comment]
Thanks. I'm also having some issues building the project. I saw there is a .pro file but it tries to include the `script` module, which doesn't exist with Qt6. I'm on Linux, so Visual Studio is not an option.

**Comment by DavidXanatos** [comment]
You can remove the script module and add the NO_QT_SCRIPT preprocessed definition instead, then it should build without it, I haven't tested it recently though the pro file is from a decade ago when I used to build the project this was originally for on other platforms.
That said the V4 part is missing a pro file entirely, so you will need to make your own, or I could make one on commission for you.

**Comment by Jmgr** [comment]
Thanks, I'll try that.
My project is using CMake actually, but since I saw a .pro file I thought I'll try with QMake first. Thank you for the offer, but that would be for a hobby open-source project, so I'm afraid I don't have a budget for commissions unfortunately :confused:
